# Generated by Django 3.1.3 on 2021-06-10 06:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BANKNIFTY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BANKNIFTY', max_length=15, null=True)),
                ('starttime', models.TimeField(default=datetime.datetime(2021, 6, 10, 6, 42, 32, 350159, tzinfo=utc))),
                ('CopenInterest', models.FloatField()),
                ('CchangeinOpenInterest', models.FloatField()),
                ('CtotalTradedVolume', models.FloatField()),
                ('CimpliedVolatility', models.FloatField()),
                ('ClastPrice', models.FloatField()),
                ('Cchange', models.FloatField()),
                ('CbidQty', models.FloatField()),
                ('Cbidprice', models.FloatField()),
                ('CaskPrice', models.FloatField()),
                ('CaskQty', models.FloatField()),
                ('strikePrice', models.FloatField()),
                ('PbidQty', models.FloatField()),
                ('Pbidprice', models.FloatField()),
                ('PaskPrice', models.FloatField()),
                ('PaskQty', models.FloatField()),
                ('Pchange', models.FloatField()),
                ('PlastPrice', models.FloatField()),
                ('PimpliedVolatility', models.FloatField()),
                ('PtotalTradedVolume', models.FloatField()),
                ('PchangeinOpenInterest', models.FloatField()),
                ('PopenInterest', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FINNIFTY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='FINNIFTY', max_length=15, null=True)),
                ('starttime', models.TimeField(default=datetime.datetime(2021, 6, 10, 6, 42, 32, 350159, tzinfo=utc))),
                ('CopenInterest', models.FloatField()),
                ('CchangeinOpenInterest', models.FloatField()),
                ('CtotalTradedVolume', models.FloatField()),
                ('CimpliedVolatility', models.FloatField()),
                ('ClastPrice', models.FloatField()),
                ('Cchange', models.FloatField()),
                ('CbidQty', models.FloatField()),
                ('Cbidprice', models.FloatField()),
                ('CaskPrice', models.FloatField()),
                ('CaskQty', models.FloatField()),
                ('strikePrice', models.FloatField()),
                ('PbidQty', models.FloatField()),
                ('Pbidprice', models.FloatField()),
                ('PaskPrice', models.FloatField()),
                ('PaskQty', models.FloatField()),
                ('Pchange', models.FloatField()),
                ('PlastPrice', models.FloatField()),
                ('PimpliedVolatility', models.FloatField()),
                ('PtotalTradedVolume', models.FloatField()),
                ('PchangeinOpenInterest', models.FloatField()),
                ('PopenInterest', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NIFTY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NIFTY', max_length=15, null=True)),
                ('starttime', models.TimeField(default=datetime.datetime(2021, 6, 10, 6, 42, 32, 310164, tzinfo=utc))),
                ('CopenInterest', models.FloatField()),
                ('CchangeinOpenInterest', models.FloatField()),
                ('CtotalTradedVolume', models.FloatField()),
                ('CimpliedVolatility', models.FloatField()),
                ('ClastPrice', models.FloatField()),
                ('Cchange', models.FloatField()),
                ('CbidQty', models.FloatField()),
                ('Cbidprice', models.FloatField()),
                ('CaskPrice', models.FloatField()),
                ('CaskQty', models.FloatField()),
                ('strikePrice', models.FloatField()),
                ('PbidQty', models.FloatField()),
                ('Pbidprice', models.FloatField()),
                ('PaskPrice', models.FloatField()),
                ('PaskQty', models.FloatField()),
                ('Pchange', models.FloatField()),
                ('PlastPrice', models.FloatField()),
                ('PimpliedVolatility', models.FloatField()),
                ('PtotalTradedVolume', models.FloatField()),
                ('PchangeinOpenInterest', models.FloatField()),
                ('PopenInterest', models.FloatField()),
            ],
        ),
    ]
