from django.db import models
import datetime
import pytz
# Create your models here.
IST = pytz.timezone('Asia/Kolkata')
class NIFTY(models.Model):
    name=models.CharField(default="NIFTY",null=True,max_length=15)
    starttime=models.TimeField(default=datetime.datetime.now(IST))
    CopenInterest=models.FloatField()
    CchangeinOpenInterest=models.FloatField()
    CtotalTradedVolume=models.FloatField()
    CimpliedVolatility=models.FloatField()
    ClastPrice=models.FloatField()
    Cchange=models.FloatField()
    CbidQty=models.FloatField()
    Cbidprice=models.FloatField()
    CaskPrice=models.FloatField()
    CaskQty=models.FloatField()
    strikePrice=models.FloatField()
    PbidQty=models.FloatField()
    Pbidprice=models.FloatField()
    PaskPrice=models.FloatField()
    PaskQty=models.FloatField()
    Pchange=models.FloatField()
    PlastPrice=models.FloatField()
    PimpliedVolatility=models.FloatField()
    PtotalTradedVolume=models.FloatField()
    PchangeinOpenInterest=models.FloatField()
    PopenInterest=models.FloatField()
class FINNIFTY(models.Model):
    name=models.CharField(default="FINNIFTY",null=True,max_length=15)
    starttime=models.TimeField(default=datetime.datetime.now(IST))
    CopenInterest=models.FloatField()
    CchangeinOpenInterest=models.FloatField()
    CtotalTradedVolume=models.FloatField()
    CimpliedVolatility=models.FloatField()
    ClastPrice=models.FloatField()
    Cchange=models.FloatField()
    CbidQty=models.FloatField()
    Cbidprice=models.FloatField()
    CaskPrice=models.FloatField()
    CaskQty=models.FloatField()
    strikePrice=models.FloatField()
    PbidQty=models.FloatField()
    Pbidprice=models.FloatField()
    PaskPrice=models.FloatField()
    PaskQty=models.FloatField()
    Pchange=models.FloatField()
    PlastPrice=models.FloatField()
    PimpliedVolatility=models.FloatField()
    PtotalTradedVolume=models.FloatField()
    PchangeinOpenInterest=models.FloatField()
    PopenInterest=models.FloatField()
class BANKNIFTY(models.Model):
    name=models.CharField(default="BANKNIFTY",null=True,max_length=15)
    starttime=models.TimeField(default=datetime.datetime.now(IST))
    CopenInterest=models.FloatField()
    CchangeinOpenInterest=models.FloatField()
    CtotalTradedVolume=models.FloatField()
    CimpliedVolatility=models.FloatField()
    ClastPrice=models.FloatField()
    Cchange=models.FloatField()
    CbidQty=models.FloatField()
    Cbidprice=models.FloatField()
    CaskPrice=models.FloatField()
    CaskQty=models.FloatField()
    strikePrice=models.FloatField()
    PbidQty=models.FloatField()
    Pbidprice=models.FloatField()
    PaskPrice=models.FloatField()
    PaskQty=models.FloatField()
    Pchange=models.FloatField()
    PlastPrice=models.FloatField()
    PimpliedVolatility=models.FloatField()
    PtotalTradedVolume=models.FloatField()
    PchangeinOpenInterest=models.FloatField()
    PopenInterest=models.FloatField()